package com.sfwl.wuliubao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sfwl.wuliubao.dao.Location;
import com.sfwl.wuliubao.dao.Users;
import com.sfwl.wuliubao.dao.Town;

import com.sfwl.wuliubao.dao.LocationDao;
import com.sfwl.wuliubao.dao.UsersDao;
import com.sfwl.wuliubao.dao.TownDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;
    private final DaoConfig usersDaoConfig;
    private final DaoConfig townDaoConfig;

    private final LocationDao locationDao;
    private final UsersDao usersDao;
    private final TownDao townDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        townDaoConfig = daoConfigMap.get(TownDao.class).clone();
        townDaoConfig.initIdentityScope(type);

        locationDao = new LocationDao(locationDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);
        townDao = new TownDao(townDaoConfig, this);

        registerDao(Location.class, locationDao);
        registerDao(Users.class, usersDao);
        registerDao(Town.class, townDao);
    }
    
    public void clear() {
        locationDaoConfig.getIdentityScope().clear();
        usersDaoConfig.getIdentityScope().clear();
        townDaoConfig.getIdentityScope().clear();
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public TownDao getTownDao() {
        return townDao;
    }

}
