package com.sfwl.wuliubao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCATION".
 */
public class Location {

    private Long id;
    private Integer userId;
    private Double locLon;
    private Double locLat;
    private String locRegion;
    private java.util.Date locTime;
    private java.util.Date sysTime;
    private Boolean sync;

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, Integer userId, Double locLon, Double locLat, String locRegion, java.util.Date locTime, java.util.Date sysTime, Boolean sync) {
        this.id = id;
        this.userId = userId;
        this.locLon = locLon;
        this.locLat = locLat;
        this.locRegion = locRegion;
        this.locTime = locTime;
        this.sysTime = sysTime;
        this.sync = sync;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Double getLocLon() {
        return locLon;
    }

    public void setLocLon(Double locLon) {
        this.locLon = locLon;
    }

    public Double getLocLat() {
        return locLat;
    }

    public void setLocLat(Double locLat) {
        this.locLat = locLat;
    }

    public String getLocRegion() {
        return locRegion;
    }

    public void setLocRegion(String locRegion) {
        this.locRegion = locRegion;
    }

    public java.util.Date getLocTime() {
        return locTime;
    }

    public void setLocTime(java.util.Date locTime) {
        this.locTime = locTime;
    }

    public java.util.Date getSysTime() {
        return sysTime;
    }

    public void setSysTime(java.util.Date sysTime) {
        this.sysTime = sysTime;
    }

    public Boolean getSync() {
        return sync;
    }

    public void setSync(Boolean sync) {
        this.sync = sync;
    }

}
