package com.sfwl.wuliubao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TOWN".
 */
public class Town {

    private Long townId;
    private String townName;
    private Integer disId;
    private Integer townSort;
    private Double longitude;
    private Double latitude;
    private Integer cityId;
    private Integer proId;
    private String parentIds;
    private String parentNames;

    public Town() {
    }

    public Town(Long townId) {
        this.townId = townId;
    }

    public Town(Long townId, String townName, Integer disId, Integer townSort, Double longitude, Double latitude, Integer cityId, Integer proId, String parentIds, String parentNames) {
        this.townId = townId;
        this.townName = townName;
        this.disId = disId;
        this.townSort = townSort;
        this.longitude = longitude;
        this.latitude = latitude;
        this.cityId = cityId;
        this.proId = proId;
        this.parentIds = parentIds;
        this.parentNames = parentNames;
    }

    public Long getTownId() {
        return townId;
    }

    public void setTownId(Long townId) {
        this.townId = townId;
    }

    public String getTownName() {
        return townName;
    }

    public void setTownName(String townName) {
        this.townName = townName;
    }

    public Integer getDisId() {
        return disId;
    }

    public void setDisId(Integer disId) {
        this.disId = disId;
    }

    public Integer getTownSort() {
        return townSort;
    }

    public void setTownSort(Integer townSort) {
        this.townSort = townSort;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public Integer getProId() {
        return proId;
    }

    public void setProId(Integer proId) {
        this.proId = proId;
    }

    public String getParentIds() {
        return parentIds;
    }

    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    public String getParentNames() {
        return parentNames;
    }

    public void setParentNames(String parentNames) {
        this.parentNames = parentNames;
    }

}
