package com.sfwl.wuliubao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USERS".
 */
public class Users {

    private Long id;
    private Integer userId;
    private String userNo;
    private Integer typeId;
    private Integer userStatu;
    private String userName;
    private String userNick;
    private String userSex;
    private String birthDate;
    private Double amount;
    private Double integral;
    private String userType;
    private String userIcon;
    private Integer level;
    private Integer groupId;
    private Integer classId;
    private String region;
    private String addres;
    private String phoneNo;
    private String mobileNo;
    private String eMail;
    private String loginTime;
    private String loginIMEI;
    private String loginPhone;
    private String wxId;
    private String aliPayId;
    private String departMent;
    private String signLabel;
    private String lastLoginDate;
    private String aliPushDeviceId;
    private String locLon;
    private String locLat;
    private String locRegion;
    private String locTime;
    private String note1;
    private String note2;
    private String note3;
    private String note4;
    private String note5;
    private String note6;
    private String note7;
    private String note8;
    private String note9;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, Integer userId, String userNo, Integer typeId, Integer userStatu, String userName, String userNick, String userSex, String birthDate, Double amount, Double integral, String userType, String userIcon, Integer level, Integer groupId, Integer classId, String region, String addres, String phoneNo, String mobileNo, String eMail, String loginTime, String loginIMEI, String loginPhone, String wxId, String aliPayId, String departMent, String signLabel, String lastLoginDate, String aliPushDeviceId, String locLon, String locLat, String locRegion, String locTime, String note1, String note2, String note3, String note4, String note5, String note6, String note7, String note8, String note9) {
        this.id = id;
        this.userId = userId;
        this.userNo = userNo;
        this.typeId = typeId;
        this.userStatu = userStatu;
        this.userName = userName;
        this.userNick = userNick;
        this.userSex = userSex;
        this.birthDate = birthDate;
        this.amount = amount;
        this.integral = integral;
        this.userType = userType;
        this.userIcon = userIcon;
        this.level = level;
        this.groupId = groupId;
        this.classId = classId;
        this.region = region;
        this.addres = addres;
        this.phoneNo = phoneNo;
        this.mobileNo = mobileNo;
        this.eMail = eMail;
        this.loginTime = loginTime;
        this.loginIMEI = loginIMEI;
        this.loginPhone = loginPhone;
        this.wxId = wxId;
        this.aliPayId = aliPayId;
        this.departMent = departMent;
        this.signLabel = signLabel;
        this.lastLoginDate = lastLoginDate;
        this.aliPushDeviceId = aliPushDeviceId;
        this.locLon = locLon;
        this.locLat = locLat;
        this.locRegion = locRegion;
        this.locTime = locTime;
        this.note1 = note1;
        this.note2 = note2;
        this.note3 = note3;
        this.note4 = note4;
        this.note5 = note5;
        this.note6 = note6;
        this.note7 = note7;
        this.note8 = note8;
        this.note9 = note9;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserNo() {
        return userNo;
    }

    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    public Integer getTypeId() {
        return typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public Integer getUserStatu() {
        return userStatu;
    }

    public void setUserStatu(Integer userStatu) {
        this.userStatu = userStatu;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserNick() {
        return userNick;
    }

    public void setUserNick(String userNick) {
        this.userNick = userNick;
    }

    public String getUserSex() {
        return userSex;
    }

    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    public String getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Double getIntegral() {
        return integral;
    }

    public void setIntegral(Double integral) {
        this.integral = integral;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getUserIcon() {
        return userIcon;
    }

    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getAddres() {
        return addres;
    }

    public void setAddres(String addres) {
        this.addres = addres;
    }

    public String getPhoneNo() {
        return phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public String getEMail() {
        return eMail;
    }

    public void setEMail(String eMail) {
        this.eMail = eMail;
    }

    public String getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime;
    }

    public String getLoginIMEI() {
        return loginIMEI;
    }

    public void setLoginIMEI(String loginIMEI) {
        this.loginIMEI = loginIMEI;
    }

    public String getLoginPhone() {
        return loginPhone;
    }

    public void setLoginPhone(String loginPhone) {
        this.loginPhone = loginPhone;
    }

    public String getWxId() {
        return wxId;
    }

    public void setWxId(String wxId) {
        this.wxId = wxId;
    }

    public String getAliPayId() {
        return aliPayId;
    }

    public void setAliPayId(String aliPayId) {
        this.aliPayId = aliPayId;
    }

    public String getDepartMent() {
        return departMent;
    }

    public void setDepartMent(String departMent) {
        this.departMent = departMent;
    }

    public String getSignLabel() {
        return signLabel;
    }

    public void setSignLabel(String signLabel) {
        this.signLabel = signLabel;
    }

    public String getLastLoginDate() {
        return lastLoginDate;
    }

    public void setLastLoginDate(String lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    public String getAliPushDeviceId() {
        return aliPushDeviceId;
    }

    public void setAliPushDeviceId(String aliPushDeviceId) {
        this.aliPushDeviceId = aliPushDeviceId;
    }

    public String getLocLon() {
        return locLon;
    }

    public void setLocLon(String locLon) {
        this.locLon = locLon;
    }

    public String getLocLat() {
        return locLat;
    }

    public void setLocLat(String locLat) {
        this.locLat = locLat;
    }

    public String getLocRegion() {
        return locRegion;
    }

    public void setLocRegion(String locRegion) {
        this.locRegion = locRegion;
    }

    public String getLocTime() {
        return locTime;
    }

    public void setLocTime(String locTime) {
        this.locTime = locTime;
    }

    public String getNote1() {
        return note1;
    }

    public void setNote1(String note1) {
        this.note1 = note1;
    }

    public String getNote2() {
        return note2;
    }

    public void setNote2(String note2) {
        this.note2 = note2;
    }

    public String getNote3() {
        return note3;
    }

    public void setNote3(String note3) {
        this.note3 = note3;
    }

    public String getNote4() {
        return note4;
    }

    public void setNote4(String note4) {
        this.note4 = note4;
    }

    public String getNote5() {
        return note5;
    }

    public void setNote5(String note5) {
        this.note5 = note5;
    }

    public String getNote6() {
        return note6;
    }

    public void setNote6(String note6) {
        this.note6 = note6;
    }

    public String getNote7() {
        return note7;
    }

    public void setNote7(String note7) {
        this.note7 = note7;
    }

    public String getNote8() {
        return note8;
    }

    public void setNote8(String note8) {
        this.note8 = note8;
    }

    public String getNote9() {
        return note9;
    }

    public void setNote9(String note9) {
        this.note9 = note9;
    }

}
